---
title: "grade"
author: "MOHAMED Maël"
format: html
---

Preliminary and question 1:

```{r}
#| message: false
here::i_am("grade.Rproj")
library(here)
library(ggplot2)
library(vroom)
library(dplyr)
library(tidyr)
library(readr)
grade <- read_delim("grades.csv")
```

Question 2:

Since each row have a grade, we can use the following code

```{r}
nrow(grade)
```

The data set contains 40 836 grades.

Question 3:

```{r}
grade |>
distinct(id) |>
nrow() 
```

The number of students in the dataset is 716.

Question 4:



```{r}
students <- grade |>
 group_by(id,group) |>
 distinct(id, .keep_all = TRUE)
  
```


```{r}
students |>
slice_tail(n = 5) |>
knitr::kable()

```

Question 5:

```{r}
ggplot(students, aes(group)) +
  geom_bar()
```


Question 6:

```{r}
students |>
  summarise(mean(students)) |>
slice_tail(n = 5) |>
knitr::kable()
```

Question 7:

```{r}
ggplot(students, aes(x = grade, fill = trimester)) +
  geom_bar()
```


Question 8:

```{r}
grade |>
  group_by(id, group) |>
  summarise(mean(grade), max(grade), min(grade)) |>
  slice_tail(n = 5) |>
knitr::kable()
```

| Statistic   | Value |
|-------------|-------|
| mean(grade) |       |
| max(grade)  |       |
| min(grade)  |       |


Question 9:

```{r}
new_grade <- grade |>
  group_by(id) |>
  mutate(n=nrow(grade))
new_grade
```

Question 12:

```{r}
grade2 <- grade |>
  group_by(course) |>
  summarise(id, group, mean(grade))
grade2
```







